### ISSUE TITLE
Docstring layout in the doc page 

### ISSUE THREAD

**Issue by Angchau** [flojoy-io/docs#168]
When the docstring is imported from the Python script to the doc section, the layout is lost and it creates a text block that is not easily readable (Problems with the parameters).

**Comment by jackparmer** [comment]
we'll need a custom MDX component for this I think that does custom parsing on the numpy docstring format. I don't think anything like this exists off the shelf now b/c the np docstring format is not super common ASFAIK

**Comment by jackparmer** [comment]
fixed via https://github.com/flojoy-io/docs/commit/56f152277a519ce826821ad30dfbce40d8454308
