### ISSUE TITLE
paths to github files should be links

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/docs#24]
the `studio` repo is public now, so any github file paths should be turned into links

this page has lots, for example:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/1865834/235801690-4a25d8cf-5a58-4509-9164-b7d6cb20063f.png">

**Comment by trbritt** [comment]
Addressed by [e41f8ea](https://github.com/flojoy-io/docs/commit/e41f8ea1c2ec91e52cde442f46f10e940206ed1f).
